# ======================= 站点 =======================
# 站点名称
WebsiteName = "我的博客"
# 监听地址
Listen = "127.0.0.1:3000"

# ====================== 博文内容 =======================
# 文章目录
ArticleDir = "articles"
# 文章中引用资源路径，比如图片
# 不支持和文章指定相同目标
ArticleReferenceDir = "articles/assets"

# ======================= 外观 =======================
# 网站页脚内容
# 需要实现`ArticleDir`/footer.md 
CustomWebsiteFooter = true
# 网站无法找到页面
# 需要实现`ArticleDir`/404.md
CustomWebsite404 = true
# 每页显示文章数
PageSize = 3
# 定义文章分类别名
# 定义多个Cateory，Path重复将产生覆盖
# [[Category]]
# 分类名称，默认取Path
# Name = "短类名"
# 所在路径，基于ArticleDir的相对路径
# Path = "我/的/名字/很长"

# ====================== 博文样式=======================
# 文章内代码语法高亮风格
# 取值范围：https://xyproto.github.io/splash/docs/all.html
ArticleCodeStyle = "perldoc"
# 文章内代码显示行号
ArticleCodeShowLineNumber = true
# 文章支持MathJax，详情参见：https://github.com/litao91/goldmark-mathjax
ArticleMathJax = true


